name: Deploy Hexo-Project to GitHub-Pages
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: [step1]checkout
        uses: actions/checkout@master

      - name: [step2]build-and-deploy
        uses: theme-keep/hexo-deploy-github-pages-action@master
        env:
          PERSONAL_TOKEN: ${{ secrets.HEXO_DEPLOY }}
          PUBLISH_REPOSITORY: chasehu123/chasehu123.github.io
          BRANCH: gh-pages
          PUBLISH_DIR: ./public